

from setuptools import setup

setup(
    author="Lukasz Mentel",
    author_email="lmmentel@gmail.com",
    packages=['asetools', 'asetools/db'],
    include_package_data=True,
    install_requires = ['builtins',
                        'numpy',
                        'scipy',
                        'pandas',
                        'sqlalchemy',
                        'alembic',
                        'ase',
                        'matplotlib'],
    entry_points={
        'console_scripts': [
            'submitQE = asetools.submit:main',
            'dbadd = asetools.db.dbinterface:add_system',
            'trajextract = asetools.cli:trajextract',
            'traj2car = asetools.cli:traj_to_car',
            'aseconvert = asetools.cli:aseconvert',
            'modifycell = asetools.cli:modify_cell',
            'asetemplate = asetools.cli:render_template',
            'getEpot = asetools.cli:get_potential_energy',
            'getCell = asetools.cli:get_cell',
            'rmsd = asetools.cli:rmsdcli',
        ]
    },
    scripts=[
        'scripts/checkpointNEB',
        'scripts/checkpointQE',
        'scripts/cubecutperiodic',
        'scripts/displayDOS',
        'scripts/displayDOS_gpaw',
        'scripts/dynmatsimple',
        'scripts/genCHG',
        'scripts/genopt_zeoliteonly',
        'scripts/getAtomindices',
        'scripts/getDPE',
        'scripts/getStructDiff',
        'scripts/getads',
        'scripts/getads_screen',
        'scripts/getadsgrid',
        'scripts/getmaxforce',
        'scripts/insertadsZSM22',
        'scripts/insertadsZSM22poremouth',
        'scripts/interpolate',
        'scripts/makejmolscript',
        'scripts/massCommand',
        'scripts/parseErr',
        'scripts/piddir',
        'scripts/printIRspec',
        'scripts/printNEBxyzs',
        'scripts/printPics',
        'scripts/printZSM22jmol',
        'scripts/printbcharges',
        'scripts/pwlog2traj',
        'scripts/rerunBEEF',
        'scripts/rerunBEEF_neb',
        'scripts/rerunBEEF_newunit',
        'scripts/restartNEB',
        'scripts/restartcalc',
        'scripts/runDOS',
        'scripts/runDOS_gpaw',
        'scripts/runDPE_QE',
        'scripts/runNCIplot',
        'scripts/runQE',
        'scripts/run_gencube',
        'scripts/writecif',
        'scripts/writeqespec',
    ],
    description="convenience scripts for ASE",
    license=open("LICENSE.txt", "r").read(),
    long_description=open("README.md", "r").read(),
    name="asetools",
    url="www.bitbucket.org/lukaszmentel/asetools",
    version="0.2.3",
)
