#!/bin/tcsh
set a = `bjobs | grep RUN`
set i = 1
while ( $i < $#a )
	set out = `cdp $a[$i];grep BFGS *log | tail -1`
	set out2 = `cdp $a[$i];grep iter *txt | tail -1`
	echo $a[$i]  '  ' $out
	echo $a[$i]  '  ' $out2
 	@ i = $i + 10
end
