#!/usr/local/bin/python2.7
#Script used to display DOS
from string import Template
import os,errno
from matplotlib import pyplot
from sys import argv,exit
from commands import getoutput
from ase import Atoms
from ase.io import read,write
from mypython import get_selected_atom_indices,get_pdos_from_files

angulars = list(argv[1].translate(None,',[]'))
atoms = read('gpaw.txt')
atomnolist = [int(a) for a in argv[2:]] #get_selected_atom_indices(atoms,argv[2])

pwd = os.getcwd()+'/'

fig = pyplot.figure()
ax = fig.add_subplot(111,xlabel='Energy relative to the Fermi level (eV)')
legends = []

for atomno in atomnolist:
   for angular in angulars:
	energy,pdos = get_pdos_from_files(pwd,atomno,angular)	
	ax.plot(energy,pdos)
	legends.append('%s, %s' % (atomno,angular))

pyplot.legend(legends,'best')
ax.grid()
pyplot.show()
