#!/usr/bin/env python
#Script used to display DOS
from string import Template
import os,errno,pickle
from matplotlib import pyplot
from sys import argv,exit
from mypython import get_resov_dos_espresso

angulars = list(argv[1].translate(None,',[]'))
atomnolist = [int(a) for a in argv[2:]]

dir = os.getcwd()+'/' #could be replaced by an argument

adict = {'p':1,'d':2,'f':3}

fig = pyplot.figure()
ax = fig.add_subplot(111)
ax.set_xlabel('Energy relative to the Fermi level (eV)')
ax.set_ylabel('PDOS (Arb. Unit)')
ax.set_title(dir.split('brogaard')[1])

legends = []

f = open(dir+'dos.pckl')
energies, dos, pdos = pickle.load(f)
f.close()

for atomno in atomnolist:
   for angular in angulars:
	resov_dos = get_resov_dos_espresso(pdos,atomno,angular)
	ax.plot(energies,resov_dos)
	legends.append('%s, %s' % (atomno,angular))

pyplot.legend(legends,'best')
ax.grid()
pyplot.show()
