#!/bin/tcsh
#Wrapper script for submission of QE jobs on abel

echo submitQE 
set a = `esp-ver-bsub $ver -n $2 -q $3 -o out.log python $input`
set a = `echo $a | grep -oE "[[:digit:]]{1,}"`
set pid = `echo $a | awk '{print $1}'`
echo $pid
set date=`date`
echo $pid $PWD $input $date >> $HOME/submitted_files.dat
