#!/usr/bin/env python
#Script used to prepare for an optimization of the silicious structure part of an adsorption complex involving a hydrocarbon adsorbate. 

from string import Template
import os,errno
from sys import argv,exit
from commands import getoutput
from ase import Atoms
from ase.io import read,write
from asetools import get_indices_by_symbols,mymkdir

#Generate startguess, i.e. atoms set without hydrocarbon atoms
atoms = read('dyn.traj')
indices = get_indices_by_symbols(atoms,['C','H'])
#NB NB, danger! If the hydrocarbon atoms do not have sequential indices this will fail
del atoms[indices[0]:indices[-1]+1]

try:
  os.mkdir('opt_zeoliteonly')
except OSError, e:
  if e.errno != errno.EEXIST: #any other error is safely reported
            raise
  print 'opt_zeoliteonly already exists. Exiting...'
  exit(errno.EEXIST)

os.chdir('opt_zeoliteonly')
write('startguess.traj',atoms)

# Import the template into a template object.
tdir = '/a/suncatfs1/u1/brogaard/bin/asetools/'
f = open(tdir+'QEopt_template.py','r')
template = Template(f.read())
f.close()
del f

f = open('input.py','w')
f.write(template.substitute(pw='400',xc='BEEF',kpts='(1,1,1)',cell='atoms.get_cell()',readpath='startguess.traj',fmax='0.03'))
f.close()
del f

os.chdir('..')
