#!/usr/local/bin/python2.7
#Script used to prepare for an optimization of the silicious structure part of an adsorption complex involving a hydrocarbon adsorbate. 

from string import Template
import os,errno
from sys import argv,exit
from commands import getoutput
from ase import Atoms
from ase.io import read,write
from mypython import get_selected_atom_indices,mymkdir

#Generate startguess, i.e. atoms set without hydrocarbon atoms
atoms = read('dyn.traj')
indices = get_selected_atom_indices(atoms,['C','H'])
#NB NB, danger! If the hydrocarbon atoms do not have sequential indices this will fail
del atoms[indices[0]:indices[-1]+1]

try:
  os.mkdir('opt_zeoliteonly')
except OSError, e:
  if e.errno != errno.EEXIST: #any other error is safely reported
            raise
  print 'opt_zeoliteonly already exists. Exiting...'
  exit(errno.EEXIST)

os.chdir('opt_zeoliteonly')
write('startguess.traj',atoms)

# Import the template into a template object.
tdir = '/a/suncatfs1/u1/brogaard/bin/mypython/'
f = open(tdir+'ZSM22_BEEFsingle_template.py','r')
template = Template(f.read())
f.close()
del f

f = open('input.py','w')
f.write(template.substitute(readpath='startguess.traj'))
f.close()
del f

os.chdir('..')
