#!/usr/bin/env python

from ase.io import read
from sys import argv
import numpy as np

if len(argv) > 1:
  fnames = argv[1:]
else:
  fnames = ['dyn.traj']

for fname in fnames:
  a = read(fname)
  try:
    forceline = ' (force: %.3f eV/AA)' % np.sqrt(np.sum(a.get_forces()**2.,axis=1)).max()
  except:
    forceline = ' (Couldn\'t read the force)'
  print fname,a.get_potential_energy(),'eV',forceline
