#!/usr/bin/env python
#Script to get the magnetic moment of a numbered atom in a trajectory file. Assumes that there is a dyn.traj file in the execution directory
from ase.io import read
from sys import argv

index = int(argv[1])
atoms = read('dyn.traj')
print atoms.get_magnetic_moments()[index]

