#!/usr/bin/env python
#Script used to generate a .traj file corresponding to a structure that is a linear interpolation in cartesian coordinates of two structures read from input file arguments
from ase.io import read,write
from asetools import interp_positions
from sys import argv
from optparse import OptionParser

parser = OptionParser(usage='Script used to create linearly interpolated images between a start and an end point.')

parser.add_option('-o','--outputname', dest='outname',default=None,
                  help='Prefix of output files. Default=inputfile1.')
parser.add_option('-n','--noimages', dest='no',default=1,
                  help='No of interpolated images. Default=1.')

options,args = parser.parse_args()

image1 = read(args[0])
image2 = read(args[1])

images = interp_positions(image1,image2,no=int(options.no))

if options.outname:
   outname = options.outname
else:
   outname = args[0].split('.')[0]

for i,image in enumerate(images):
  write(outname+'%s.traj' % (i+1),image)

