#!/usr/bin/python
import sys

errfile = sys.argv[1]
f = open(errfile)
lines = f.read().split('\n')
f.close()
uniques = []
for line in lines:
    if line not in uniques:
        uniques.append(line)
for line in uniques:
    print line
