#!/usr/local/bin/python2.7
#/usr/bin/env python
#Script used to run a frequency calculation of an organic molecule contained in another unit
from sys import argv
from mypython import get_selected_atom_indices
from ase.io import read
import os

#get indices for C,N,O and H atoms
indices = get_selected_atom_indices(read('dyn.traj'),['C','N','H'])

runstr = 'run_frequencies_gpaw --indices=\''+str(indices)+'\' '+' '.join(map(str,argv[1:]))
os.system(runstr)
