#!/usr/bin/env python
#Script used to run a frequency calculation of a hydrocarbon contained in another unit
from sys import argv
from mypython import get_selected_atom_indices
from ase.io import read
import os
import numpy as np

#get indices for C,N and H atoms
indices = get_selected_atom_indices(read('dyn.traj'),['C','N','H'])
if '--native' in argv[1:]: #espresso numbers atoms from 1, not from 0 like ASE
   indices = [x+1 for x in indices]

runstr = 'run_frequencies --indices=\''+str(indices)+'\' '+' '.join(map(str,argv[1:]))
os.system(runstr)
