#!/usr/bin/env python
#Script writing a set of images from a .traj file in the cwd
from mypython import printPics,mymkdir
from sys import argv
from ase.io import read,write
import os
from optparse import OptionParser

parser = OptionParser(usage='Script for printing images or xyz files of the output from an ASE calculation on a ZSM22 zeolite, in selected perspectives')
parser.add_option('-d','--dir', dest='outdir',default=os.getcwd()+'/',
                  help='choose output directory (will be made if not present)')
parser.add_option('-i','--input', dest='readname',default='dyn',
                  help='set input/output file basename')
parser.add_option('-o','--output', dest='writename',default='',
                  help='set output file basename')
parser.add_option('-f','--format', dest='format',default='eps',
                  help='set output file format')

(options,args) = parser.parse_args()
print options

#Not very elegant way of making the default output name equal the input
if options.writename == '':
    options.writename = options.readname

atoms = read(options.readname+'.traj')
specs = []
    specs.append(('front','180y,55z',atoms))
    specs.append(('back','-55z',atoms))
    specs.append(('siteside','-90y,60x',geometry.cut(atoms,a=(-1.,0,0), b=(-0.35,0.7,0), c=(0,0,1),origo=(1.,0,0))))
    specs.append(('sitetop','90y',geometry.cut(atoms,a=(2./3.,0,0), b=(0,1.,0), c=(0,0,1),origo=(1./3.,0,0))))
printPics(atoms,specs=specs,basename=options.writename,outdir=options.outdir,filetype=options.format)

