#!/usr/bin/env python
#Script used to rerun BEEF calculations on molecules
from string import Template
import os
from sys import argv

#path = argv[1]
#print 'path',path
try:
    n_cpu = argv[1]
    print 'n_cpu:',n_cpu
except IndexError:
    print 'using default n_cpu = 12'
    n_cpu = 12
try:
    queue = argv[2]
    print 'queue:',queue
except IndexError:
    print 'using default queue = suncat2-medium'
    queue = 'suncat2-medium'

os.mkdir('rerunsimplecalc')
os.chdir('rerunsimplecalc')

# Import the template into a template object.
f = open('/a/suncatfs1/u1/brogaard/bin/mypython/molecule_template.py','r')
template = Template(f.read())
f.close()
del f
f = open('input.py','w')
f.write(template.substitute(xc='BEEF-vdW',h='0.2',vac='5.0',readpath='../dyn.traj',pbc='False'))
f.close()
del f
os.system('gsub-sun '+str(n_cpu)+' '+queue)
os.chdir('../')

