#!/usr/local/bin/python2.7
#Script used to rerun a previous calculation on ZSM22 with BEEF-vdW/Quantum Espresso
from string import Template
import os
from sys import argv
from mypython import mymkdir

try:
    n_cpu = argv[1]
    print 'n_cpu:',n_cpu
except IndexError:
    print 'using default n_cpu = 16'
    n_cpu = 16
try:
    queue = argv[2]
    print 'queue:',queue
except IndexError:
    print 'using default queue = suncat3-medium'
    queue = 'suncat3-medium'

mymkdir('QE')
os.chdir('QE')

# Import the template into a template object.
f = open('/a/suncatfs1/u1/brogaard/bin/mypython/QEopt_template.py','r')
template = Template(f.read())
f.close()
del f
f = open('input.py','w')
f.write(template.substitute(sigma=0.1,spinpol='TRUE',xc='BEEF',kpts='(1,1,1)',pw='500',readpath='../dyn.traj',fmax='0.03'))
f.close()
del f
subcmd='esub-suncat '+str(n_cpu)+' '+queue
os.system(subcmd)
os.chdir('../')

