#!/usr/bin/env python
#Script used to rerun a previous calculation on ZSM5 with BEEF-vdW/Quantum Espresso
from string import Template
import os
from sys import argv

try:
    n_cpu = argv[1]
    print 'n_cpu:',n_cpu
except IndexError:
    print 'using default n_cpu = 12'
    n_cpu = 12
try:
    queue = argv[2]
    print 'queue:',queue
except IndexError:
    print 'using default queue = suncat2-medium'
    queue = 'suncat2-medium'

os.mkdir('QE')
os.chdir('QE')

lc = [] #unit cell lattice constants, BEEF-vdW/QE optimized

# Import the template into a template object.
f = open('/a/suncatfs1/u1/brogaard/bin/mypython/QEopt_template.py','r')
template = Template(f.read())
f.close()
del f

cell = [] #BEEF-vdW/QE optimized lattice constants from the unit cell

f = open('input.py','w')
f.write(template.substitute(xc='BEEF',kpts='(1,1,1)',pw='400',readpath='../dyn.traj',cell=str(cell),fmax='0.03'))
f.close()
del 
os.system('esp-ver-bsub 6 -n %s -q %s -o out.log input.py' % (n_cpu,queue))
os.chdir('../')

