#!/bin/sh
#Script used to rerun a calculation with BEEF in a single point
##NB NB: must be executed in the directory in which the original job
##was performed.
mkdir BEEF_single
cp submscript BEEF_single/
sed "s#\(xc='\).*\('\)#\1BEEF-vdW\2#" input.py > BEEF_single/temp
cd BEEF_single
sed "s#\(mode='\).*\('\)#\1scf\2#" temp > input.py
sed "s#\(read('\).*\(')\)#\1../dyn.traj\2#" input.py > temp
mv temp input.py
#python input.py
