#!/bin/sh
#Script to submit a restart of a job
#NB NB: must be executed in the directory in which the original job
#was performed.
mv dyn.traj restart.traj
sed "s#\(read('\).*\(')\)#\1restart.traj\2#" input.py > input_temp
mv input_temp input.py
rm -fr qe[0-9]*_* slurm-*.out
submitQE input.py 
