#!/bin/sh
#Script to submit a restart of a job
#NB NB: must be executed in the directory in which the original job
#was performed.
mv dyn.traj restart.traj
sed "s#\(read('\).*\(')\)#\1restart.traj\2#" $1 > temp
mv temp $1
rm -fr qe[0-9]*_* slurm-*.out
submitQE.py $@
