#!/usr/bin/env python
#Script used to create the input file for and submit a BEEF-vdW/GPAW relaxation

from string import Template
import os,errno
from sys import argv,exit
from commands import getoutput
from ase import Atoms
from ase.io import read,write

# Import the template into a template object.
tdir = '/a/suncatfs1/u1/brogaard/bin/mypython/'
f = open(tdir+'relax_gpaw.py','r')
template = Template(f.read())
f.close()
del f

f = open('input.py','w')
f.write(template.substitute(readpath='startguess.traj',xc='BEEF-vdW',h='0.2',kpts='(1,1,1)',txt='gpaw.txt',fmax='0.01'))
f.close()
del f
os.system(' '.join(argv[1:]))

