#!/usr/bin/env python
#Script used to prepare a PBE-D calculation based on a BEEF-vdW optimized structure

from string import Template
import os,errno
from sys import argv,exit
from commands import getoutput
from ase import Atoms
from ase.io import read,write
from mypython import get_selected_atom_indices,mymkdir


try:
  os.mkdir('PBE-D')
except OSError, e:
  if e.errno != errno.EEXIST: #any other error is safely reported
            raise
  print 'Directory already exists. Exiting...'
  exit(errno.EEXIST)

os.chdir('PBE-D')

# Import the template into a template object.
del f



os.chdir('..')
