#!/bin/bash
#Script for rerunning with PBE-D a structure optimized with BEEF-vdW

mkdir PBE-D
cd PBE-D
sed s/xc=\'BEEF-vdW\',/xc=\'PBE\',vdw_corr=\'dft-d\',/ ../input.py > input.py
sed "s#\(read('\).*\(')\)#\1../dyn.traj\2#" input.py > input_temp
mv input_temp input.py
cp ../submscript .
mysbatch submscript
