#!/usr/local/bin/python2.7
#Script used to rerun a single point energy calculation with Quantum Espresso, using DFT+D (PBE+D)
from string import Template
import os
from sys import argv
from mypython import mymkdir

try:
    n_cpu = argv[1]
    print 'n_cpu:',n_cpu
except IndexError:
    print 'using default n_cpu = 16'
    n_cpu = 16
try:
    queue = argv[2]
    print 'queue:',queue
except IndexError:
    #print 'using default queue = suncat3-medium'
    queue = 'suncat3-medium'

#os.system('mv QE QE_usppv1')
mymkdir('QE_DFT-D')
os.chdir('QE_DFT-D')

# Import the template into a template object.
f = open('/a/suncatfs1/u1/brogaard/bin/mypython/QEinitializecalc_template.py','r')
template = Template(f.read())
f.close()
del f
f = open('input.py','w')
f.write(template.substitute(sigma='0.0',dw='7000',pw='500',xc='PBE',kpts='(1,1,1)',readpath='../dyn.traj'))
f.close()
del f
os.chmod('input.py',0744) #+rwx for owner, +r for rest
os.chdir('../')

