#!/usr/bin/env python
#Script used to prepare and submit an RPBE calculation based on a BEEF-vdW optimized structure

from string import Template
import os,errno
from sys import argv,exit
from commands import getoutput
from ase import Atoms
from ase.io import read,write
from mypython import get_selected_atom_indices,mymkdir

#Generate startguess, i.e. atoms set without hydrocarbon atoms

try:
  os.mkdir('RPBE')
  os.mkdir('RPBE/opt_zeoliteonly')
except OSError, e:
  if e.errno != errno.EEXIST: #any other error is safely reported
            raise
  print 'Directory already exists. Exiting...'
  exit(errno.EEXIST)

# Import the template into a template object.
tdir = '/a/suncatfs1/u1/brogaard/bin/mypython/'
f = open(tdir+'single_energy_only.py','r')
template = Template(f.read())
f.close()
del f

os.chdir('RPBE')

f = open('input.py','w')
f.write(template.substitute(readpath='../dyn.traj',func='RPBE'))
f.close()
del f
os.system(' '.join(argv[1:]))

os.chdir('opt_zeoliteonly')
f = open('input.py','w')
f.write(template.substitute(readpath='../../opt_zeoliteonly/dyn.traj',func='RPBE'))
f.close()
del f
os.system(' '.join(argv[1:]))

os.chdir('../../')
