#!/usr/bin/env python
#Script used to submit RPBE calculations 

from string import Template
import os,commands,random
from sys import argv
from mypython import mymkdir
from ase.all import *

tree = []

for root, dirs, files in os.walk('.'):
       #print 'root, dirs, files',root, dirs, files
       tree.append([root, dirs, files])

startdir = os.getcwd()
included = []
not_to_include = ['Frequencies','Barriers','opt_zeoliteonly','RPBE'] 

for m in tree:
    if 'Restart' not in m[1]:
	tag = True
        for l in m[0].split('/'):
          if l in not_to_include:
             tag = False
        if tag is True:
            for n in m[2]:
              if n == 'dyn.traj':
                a = read(os.path.join(m[0],n))
                maxforce = np.sqrt(np.sum(a.get_forces()**2.,axis=1)).max()
		if maxforce <= 0.03:
  		  if not(os.path.exists(os.path.join(m[0],'RPBE'))):
		    os.chdir(m[0])
		    os.system('runRPBE '+' '.join(argv[1:]))
	 	    os.chdir(startdir)
